class Api::EducationsController < ApplicationController
  
  #YOU LEFT OFF HERE!!!!! CREATE THE CONTROLLER, VIEW AND ROUTES.

  #YOU ALSO FORGOT TO MAKE VIEWS FOR THE EXPERIENCES CONTROLLER. MAKE THAT FIRST.
end
